---
- hosts: localhost
  become: true
  tasks:
    - name: common | set hostname
      hostname:
        name: "packer-{{ ansible_default_ipv4.address.split('.')[2] }}-{{ ansible_default_ipv4.address.split('.')[3] }}"
